// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2oq6yUZHUCcj0qaUNFpqwBhNLrKAq4pQ',
    appId: '1:952004332690:web:d8b2604256fded3651aa4b',
    messagingSenderId: '952004332690',
    projectId: 'code-ai-88d04',
    authDomain: 'code-ai-88d04.firebaseapp.com',
    storageBucket: 'code-ai-88d04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUqdJloyPUi8Qc3CKzTVfICHte-HZ6Bvc',
    appId: '1:952004332690:android:f398e182f5514a8351aa4b',
    messagingSenderId: '952004332690',
    projectId: 'code-ai-88d04',
    storageBucket: 'code-ai-88d04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy3sCE_MlQMpof7wnUwJc2LkBaKmHpQts',
    appId: '1:952004332690:ios:68024940fb9317df51aa4b',
    messagingSenderId: '952004332690',
    projectId: 'code-ai-88d04',
    storageBucket: 'code-ai-88d04.appspot.com',
    iosBundleId: 'com.example.bhcProp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy3sCE_MlQMpof7wnUwJc2LkBaKmHpQts',
    appId: '1:952004332690:ios:68024940fb9317df51aa4b',
    messagingSenderId: '952004332690',
    projectId: 'code-ai-88d04',
    storageBucket: 'code-ai-88d04.appspot.com',
    iosBundleId: 'com.example.bhcProp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2oq6yUZHUCcj0qaUNFpqwBhNLrKAq4pQ',
    appId: '1:952004332690:web:6526d8cd6455772851aa4b',
    messagingSenderId: '952004332690',
    projectId: 'code-ai-88d04',
    authDomain: 'code-ai-88d04.firebaseapp.com',
    storageBucket: 'code-ai-88d04.appspot.com',
  );
}
